[package]
name = "diesel-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[dev-dependencies]
diesel = { version = "2.2.4", features = ["postgres"] }
trybuild = "1.0.99"
