version: "0.5"

processes:
  tests:
    command: cargo test
    availability:
      exit_on_end: true
    depends_on:
      db: 
        condition: process_healthy

  db:
    command: start-db
    is_daemon: true
    shutdown:
      command: stop-db
    readiness_probe:
      exec:
        command: "pg_isready -p 5555 -h localhost"
      initial_delay_seconds: 2
      period_seconds: 2
