[profile.default]
test-threads = 1
slow-timeout = { period = "60s", terminate-after = 5, grace-period = "30s" }

[profile.release]
test-threads = 1
slow-timeout = { period = "60s", terminate-after = 5, grace-period = "30s" }
